export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_VERIFIED = "GET_VERIFIED";
export const AUTH_OTP_START = "AUTH_OTP_START";
export const CANCEL_VERIFICATION = "CANCEL_VERIFICATION";
